=== Balder86/java_test/java_test_xml/src/test/java/de/lathspell/java_test_xml/xsd2java/Items.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="Items">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="Item" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Item">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Name" />
                <xs:element ref="Price" />
            </xs:sequence>
            <xs:attribute name="id" use="required" type="xs:NCName" />
        </xs:complexType>
    </xs:element>
    
    <xs:element name="Name" type="xs:string" />
    <xs:element name="Price" type="xs:string" />
</xs:schema>

=== Balder86/java_test/java_test_xml/src/test/java/de/lathspell/java_test_xml/xsd2java/Items.xml
<Items xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='Items.xsd'>

    <Item id="LAP001">
        <Name>Laptop</Name>
        <Price>4343$</Price>
    </Item>

    <Item id="TV001">
        <Name>Television</Name>
        <Price>433$</Price>
    </Item>

    <Item id="DVD001">
        <Name>DVD Player</Name>
        <Price>763$</Price>
    </Item>

</Items>
