=== Balder86/java_test/java_test_xml/src/main/dtd/job.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ELEMENT job (customerId, objectId, date, requestor, parts)>
<!ATTLIST job
    action (create|delete) #REQUIRED
>

<!ELEMENT customerId (#PCDATA)>
<!ELEMENT objectId (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT requestor (#PCDATA)>
<!ELEMENT parts (address?, book?)>

<!ELEMENT address ((name|company), street, city)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT company (#PCDATA)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT city (#PCDATA)>

<!ELEMENT book (author, title, date)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT title (#PCDATA)>

=== Balder86/java_test/java_test_xml/src/test/resources/de/lathspell/java_test_xml/test1.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<!DOCTYPE job SYSTEM "../../../../../../src/main/dtd/job.dtd">
<job action="create">
    <customerId>12345678</customerId>
    <objectId>K24S4</objectId>
    <date>2013-08-04</date>
    <requestor>me@example.com</requestor>
    <parts>
        <address>
            <company>Example GmbH</company>
            <street>Neumarkt 1</street>
            <city>Köln</city>
        </address>
        <book>
            <author>Max Mustermann</author>
            <title>README</title>
            <date>1900-01-01</date>
        </book>
    </parts>
</job>
